### ISSUE TITLE
Issue a receipt when a payment declines (to meet Tap to Pay guidelines)

### ISSUE THREAD

**Issue by nabilfreeman** [stripe/stripe-terminal-react-native#733]
**Is your feature request related to a problem? Please describe.**
Apple's guidelines for Tap to Pay on iOS specify that it must be possible to generate a receipt for the customer when *either* a payment succeeds or *declines*.

We have covered the use case when a payment succeeds easily with the available of `receipt_url` on the payment intent.

However Stripe doesn't issue receipts when a payment is declined (or does it?).

This means that there is a mismatch between Stripe Terminal's capabilities and what Apple mandates.

**Describe the solution you'd like**
1) Tip on what to do in this specific situation, either from Stripe reps or from other TTPOI implementers who went through the Apple approval process
2) Declined receipts in Stripe

**Describe alternatives you've considered**
- Generate a basic formatted text string and allow the merchant to share it via Activity View 

**Additional context**
<img width="767" alt="Screenshot 2024-06-13 at 22 35 50" src="https://github.com/stripe/stripe-terminal-react-native/assets/2470659/d817ab28-f3f7-4c0a-a3ad-c54dc3464536">

**Comment by inzqne** [comment]
After going through Apple's absolute disaster of a checklist, I found that the easiest solution here is to create your own simple web page that displays basic receipt info, assuming that you already have some sort of web-hosted frontend. On this web page, you can fetch the payment intent info from Stripe using the intent ID that can be passed through a GET request. If status == succeeded then display basic receipt info, else state that the payment was declined.

**Comment by nabilfreeman** [comment]
Here's how we implemented this:

```typescript
import { Share } from 'react-native';

...

} catch (error) {
	showProblem({
		title: 'Payment Error',
		error,
		buttons: [
			{
				text: 'Share receipt',
				onPress: async () => {
					// prettier-ignore
					const declinedReceiptText = (
`SALE
CARDHOLDER COPY
PLEASE KEEP THIS RECEIPT FOR YOUR RECORDS
TOTAL ${payment.amount} ${payment.currency}
* THANK YOU
* ${Moment().format('HH:mm DD/MM/YY')}
************************
NOT AUTHORISED
************************`
					);

					await Share.share({
						message: declinedReceiptText,
					}).catch(error => { ... });

...
```

**Comment by nazli-stripe** [comment]
hey all, Stripe doesn't provide receipts for unsuccessful payments. As recommended you should fetch the PaymentIntent and create your own receipt for failures. Failed PaymentIntents will still have some relevant fields for receipts: https://docs.stripe.com/terminal/features/receipts#custom
